targets:
  debian-8: &debian
    build_dependencies:
      - git
      - nodejs-legacy
      - npm
  ubuntu-14.04:
    <<: *debian
  fedora-20: &fedora
    build_dependencies:
      - git
      - nodejs
      - npm
before:
  - git submodule init
  - git submodule update
  - make build-client
  - make clean-client-dist
