targets:
  debian-8: &debian
    build_dependencies:
      - nodejs-legacy
      - npm
      - git
  ubuntu-14.04:
    <<: *debian
before:
  - git submodule init
  - git submodule update
  - make build-client
after:
  - mv bin/neutron neutron
